name: Codecov
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  UnitTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.15.4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install modules
        run: pnpm install --frozen-lockfile
      - name: Run Test
        run: pnpm run coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/coverage-final.json,./coverage/index.html,./coverage/clover.html
          token: ${{ secrets.CODECOV_TOKEN }}
